### ISSUE TITLE
SyntaxError: Unexpected token import

### ISSUE THREAD

**Issue by fahadqazi** [kentcdodds/es6-workshop#50]
hi

I followed the setup process as described but when I run an individual quiz file I get this: 

`(function (exports, require, module, __filename, __dirname) { import log from './pretty-log'
                                                              ^^^^^^
SyntaxError: Unexpected token import
    at Object.exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:418:7)
    at startup (bootstrap_node.js:139:9)
    at bootstrap_node.js:533:3`

It might just be my machine of something...

Thanks

Node @ 7.5.0
yarn @ 0.19
npm @ 4.1.2

**Comment by kentcdodds** [comment]
Hi there! You shouldn't be running the quizzes yourself, but if you want to you can't run them with `node` directly. They're using ES6 code (modules) that will need to be transpiled. You'll have to run `./node_modules/.bin/babel-node path-to-file.js`. Or even better, just run `npm start quiz` and save changes to one of the quizzes.

Good luck!

**Comment by fahadqazi** [comment]
oh ok, Thanks a lot ! 👍
