### ISSUE TITLE
Syntax error on yarn run setup

### ISSUE THREAD

**Issue by 0xSventek** [kentcdodds/es6-workshop#52]
Hello,

Thank you for the workshop. I'm excited to get started. I'm hoping to get some help with the following error on initial setup:

```
$ yarn -v
n1.7.0
$ node -v
v6.14.2
$ yarn run setup
yarn run v1.7.0
$ node ./scripts/verify && node ./scripts/install && npm run validate && node ./scripts/autofill-feedback-email
/code/sandbox/es6-workshop/scripts/verify.js:22
    )
    ^

SyntaxError: Unexpected token )
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.runMain (module.js:611:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:160:9)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by kentcdodds** [comment]
You need to upgrade your version of node to 8 or greater.

**Comment by kentcdodds** [comment]
Good luck! 😀

**Comment by 0xSventek** [comment]
Thank you! It still says version 6 here: https://github.com/kentcdodds/es6-workshop#system-requirements

**Comment by kentcdodds** [comment]
I should fix this. Thanks for letting me know.
